In [1]:
import numpy as np

# Task 1

In [18]:
class MinHeap:
  def __init__(self, capacity):
    self.__heapA = [0] * (capacity + 1)
    self.__size = 0

  def insert(self, val):
    self.__size += 1
    if self.__size > (len(self.__heapA)-1):
      print("Capacity exceeded. Can't insert.")
      return
    self.__heapA[self.__size] = val
    self.swim(self.__size)

  def swim(self, idx):
    if idx == 1:
      return
    parent = idx // 2
    if self.__heapA[parent] <= self.__heapA[idx]:
      return
    else:
      temp = self.__heapA[parent]
      self.__heapA[parent] = self.__heapA[idx]
      self.__heapA[idx] = temp
      self.swim(parent)

  def extractMin(self):
    if self.__size == 0:
      return
    tempMinVal = self.__heapA[1]
    self.__heapA[1] = self.__heapA[self.__size]
    self.__heapA[self.__size] = tempMinVal
    self.__size -= 1
    self.sink(1)
    return tempMinVal

  def sink(self, idx):
    lChildIdx = 2 * idx
    rChildIdx = 2 * idx + 1

    if lChildIdx > self.__size:
        return

    minChildIdx = lChildIdx
    if rChildIdx <= self.__size and self.__heapA[rChildIdx] < self.__heapA[lChildIdx]:
        minChildIdx = rChildIdx

    if self.__heapA[idx] <= self.__heapA[minChildIdx]:
        return

    temp = self.__heapA[idx]
    self.__heapA[idx] = self.__heapA[minChildIdx]
    self.__heapA[minChildIdx] = temp

    self.sink(minChildIdx)


  def sort(self):
    newA = np.full(self.__size, 0, dtype=int)
    i = 0
    while (self.__size > 0):
      val = self.extractMin()
      newA[i] = val
      i += 1
    return newA

  def getHeap(self):
    newA = np.full(self.__size, 0, dtype=int)
    for i in range(self.__size):
        newA[i] = self.__heapA[i + 1]
    return newA

In [22]:
#Driver Code
arr = np.array([4, 2, 9, 8, 6])
theHeap = MinHeap(len(arr))
for i in range(len(arr)):
  theHeap.insert(arr[i])
print(theHeap.getHeap())
print("Sorted Heap:", end = " ")
print(theHeap.sort())

[2 4 9 8 6]
Sorted Heap: [2 4 6 8 9]


# Task 2

In [23]:
class MaxHeap:
  def __init__(self, capacity):
    self.__heapA = [0] * (capacity + 1)
    self.__size = 0

  def insert(self, val):
    self.__size += 1
    if self.__size > (len(self.__heapA)-1):
      print("Capacity exceeded. Can't insert.")
      return
    self.__heapA[self.__size] = val
    self.swim(self.__size)

  def swim(self, idx):
    if idx == 1:
      return
    parent = idx // 2
    if self.__heapA[parent] >= self.__heapA[idx]:
      return
    else:
      temp = self.__heapA[parent]
      self.__heapA[parent] = self.__heapA[idx]
      self.__heapA[idx] = temp
      self.swim(parent)

  def extractMax(self):
    if self.__size == 0:
      return
    tempMaxVal = self.__heapA[1]
    self.__heapA[1] = self.__heapA[self.__size]
    self.__heapA[self.__size] = tempMaxVal
    self.__size -= 1
    self.sink(1)
    return tempMaxVal

  def sink(self, idx):
    lChildIdx = 2 * idx
    rChildIdx = 2 * idx + 1

    if lChildIdx > self.__size:
        return

    maxChildIdx = lChildIdx
    if rChildIdx <= self.__size and self.__heapA[rChildIdx] > self.__heapA[lChildIdx]:
        maxChildIdx = rChildIdx

    if self.__heapA[idx] >= self.__heapA[maxChildIdx]:
        return

    temp = self.__heapA[idx]
    self.__heapA[idx] = self.__heapA[maxChildIdx]
    self.__heapA[maxChildIdx] = temp

    self.sink(maxChildIdx)

  def sort(self):
    newA = np.full(self.__size, 0, dtype=int)
    i = 0
    while (self.__size > 0):
      val = self.extractMax()
      newA[i] = val
      i += 1
    return newA

  def getHeap(self):
    newA = np.full(self.__size, 0, dtype=int)
    for i in range(self.__size):
        newA[i] = self.__heapA[i + 1]
    return newA

In [24]:
#Driver Code
arr = np.array([4, 2, 9, 8, 6])
theHeap = MaxHeap(len(arr))
for i in range(len(arr)):
  theHeap.insert(arr[i])
print(theHeap.getHeap())
print("Sorted Heap:", end = " ")
print(theHeap.sort())

[9 8 4 2 6]
Sorted Heap: [9 8 6 4 2]


# Task 3

In [6]:
def taskSchedular(arr, m):
  machineHeap = MinHeap(m)
  for i in range(m):
    machineHeap.insert(0)

  for j in range(len(arr)):
    minLoad = machineHeap.extractMin()
    machineHeap.insert(minLoad + arr[j])
  return machineHeap.getHeap()

#Driver Code
tasks = np.array([2, 4, 7, 1, 6])
m = 4
print(taskSchedular(tasks, m))

[2 7 4 7]


# Task 4

In [7]:
def topK(arr, k):
  theHeap = MaxHeap(len(arr))
  for i in range(len(arr)):
    theHeap.insert(arr[i])

  newA = np.zeros(k, dtype = int)

  for j in range(k):
    maxVal = theHeap.extractMax()
    newA[j] = maxVal
  return newA

#Driver Code
nums = [4, 10, 2, 8, 6, 7]
k = 3
print(topK(nums, k))

[10  8  7]
